'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import BarcodeReader from './BarcodeReader';

type Product={name:string;sku:string;category:string;stock:number;price:number;status:string;image?:string};
type Sale={id:string;items:{sku:string;name:string;quantity:number;price:number}[];total:number;payment:string;createdAt:string};
const productCategories=['Varas','Molinetes','Carretilhas','Linhas','Anzóis','Iscas','Acessórios','Caixas térmicas','Vestuário','Camping'];
const initialProducts:Product[]=[];
const nav=[['Visão geral','⌂'],['Produtos','▣'],['Vendas','↗'],['Clientes','♙'],['Fornecedores','◇'],['Relatórios','▥']];

export default function Home(){
 const [active,setActive]=useState('Visão geral'); const [query,setQuery]=useState(''); const [notice,setNotice]=useState('');
 const [products,setProducts]=useStored<Product[]>('casa-products-v4',initialProducts);
 const [sales,setSales]=useStored<Sale[]>('casa-sales-v1',[]);
 const [selling,setSelling]=useState(false);
 const filtered=useMemo(()=>products.filter(p=>(p.name+p.category+p.sku).toLowerCase().includes(query.toLowerCase())),[query,products]);
 const feedback=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(''),2400)};
 const navigate=(item:string)=>{setActive(item);setQuery('');window.scrollTo({top:0,behavior:'smooth'})};
 return <main className="app-shell"><BarcodeReader/>
  <aside className="sidebar">
   <button className="brand" onClick={()=>navigate('Visão geral')} aria-label="Ir para visão geral"><img src="/logo-casa-do-pescador.png" alt="Casa do Pescador"/><span><strong>Casa do Pescador</strong><small>Gestão da loja</small></span></button>
   <nav aria-label="Menu principal">{nav.map(([item,icon])=><button key={item} className={active===item?'active':''} onClick={()=>navigate(item)} aria-current={active===item?'page':undefined}><i>{icon}</i>{item}</button>)}</nav>
   <div className="side-bottom"><button onClick={()=>feedback('Configurações abertas')}><i>⚙</i>Configurações</button><div className="profile"><b>AP</b><span><strong>André Pescador</strong><small>Administrador</small></span><em>⋮</em></div></div>
  </aside>
  <section className="content">
   <header className="topbar"><div><p>Gestão simples, estoque sempre atualizado</p><h1>{active}</h1></div><div className="actions"><button className="bell" aria-label="Notificações" onClick={()=>feedback('Você não tem novas notificações')}>♢<i/></button><button className="primary" onClick={()=>setSelling(true)}>＋ Nova venda</button></div></header>
   <div className="dashboard">{active==='Visão geral'?<Overview navigate={navigate} products={products}/>:active==='Produtos'?<Products items={products} setItems={setProducts} filtered={filtered} query={query} setQuery={setQuery} feedback={feedback}/>:active==='Vendas'?<Sales sales={sales} onNew={()=>setSelling(true)}/>:active==='Clientes'?<Customers feedback={feedback}/>:active==='Fornecedores'?<Suppliers feedback={feedback}/>:<Reports/>}</div>
  </section>{selling&&<QuickSale products={products} onClose={()=>setSelling(false)} onComplete={(sale)=>{setProducts(products.map(p=>{const line=sale.items.find(x=>x.sku===p.sku);const stock=line?p.stock-line.quantity:p.stock;return {...p,stock,status:stock===0?'Esgotado':stock<6?'Estoque baixo':'Em estoque'}}));setSales([sale,...sales]);setSelling(false);feedback('Venda concluída e estoque atualizado')}}/>}{notice&&<div className="toast" role="status">✓ {notice}</div>}
 </main>
}

function Overview({navigate,products}:{navigate:(x:string)=>void;products:Product[]}){return <>
 <section className="welcome"><div><span>PAINEL DA LOJA</span><h2>Bom dia, André! 🎣</h2><p>Acompanhe os resultados e mantenha sua operação em dia.</p></div><img src="/logo-casa-do-pescador.png" alt=""/></section>
 <section className="stats"><Stat icon="↗" tone="orange" label="Vendas do dia" value="R$ 0,00" detail="Nenhuma venda"/><Stat icon="▣" tone="cyan" label="Pedidos" value="0" detail="Nenhum pedido"/><Stat icon="!" tone="gold" label="Produtos cadastrados" value={String(products.length)} detail="Cadastrar produto →" action={()=>navigate('Produtos')}/><Stat icon="♙" tone="olive" label="Clientes" value="0" detail="Nenhum cliente"/></section>
 <section className="middle"><article className="panel"><Title title="Desempenho de vendas" subtitle="Os resultados aparecerão após suas primeiras vendas"/><EmptyState text="Nenhuma venda registrada."/></article><article className="panel"><Title title="Vendas por categoria" subtitle="Distribuição dos seus produtos vendidos"/><EmptyState text="Ainda não há dados para exibir."/></article></section>
 <section className="panel inventory"><div className="inventory-head"><Title title="Seus produtos" subtitle="Cadastre os produtos da sua loja"/><button className="text-action" onClick={()=>navigate('Produtos')}>Cadastrar produto →</button></div>{products.length?<ProductTable items={products.slice(0,4)}/>:<EmptyState text="Você ainda não cadastrou nenhum produto."/>}</section>
 </>}

function Products({items,setItems,filtered,query,setQuery,feedback}:{items:Product[];setItems:(x:Product[])=>void;filtered:Product[];query:string;setQuery:(x:string)=>void;feedback:(x:string)=>void}){const [editing,setEditing]=useState<Product|null>(null);const save=(p:Product)=>{setItems(items.some(x=>x.sku===p.sku)?items.map(x=>x.sku===p.sku?p:x):[p,...items]);setEditing(null);feedback('Produto salvo')};const remove=(p:Product)=>{if(confirm(`Excluir ${p.name}?`)){setItems(items.filter(x=>x.sku!==p.sku));feedback('Produto excluído')}};return <Page title="Catálogo de produtos" subtitle="Gerencie preços, categorias e níveis de estoque" action="＋ Cadastrar produto" onAction={()=>setEditing({name:'',sku:`NOV-${Date.now().toString().slice(-4)}`,category:'Acessórios',stock:0,price:0,status:'Em estoque'})}><section className="stats compact"><Stat icon="▣" tone="cyan" label="Produtos cadastrados" value={String(items.length)} detail="Dados salvos no aparelho"/><Stat icon="!" tone="gold" label="Estoque baixo" value={String(items.filter(x=>x.stock>0&&x.stock<6).length)} detail="Requer atenção"/><Stat icon="×" tone="orange" label="Esgotados" value={String(items.filter(x=>x.stock===0).length)} detail="Repor estoque"/></section><section className="panel inventory product-page"><div className="inventory-head"><Title title="Todos os produtos" subtitle={`${filtered.length} produtos encontrados`}/><div className="tools"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto..."/></label></div></div><ProductTable items={filtered} onEdit={setEditing} onDelete={remove}/></section>{editing&&<ProductEditor value={editing} onClose={()=>setEditing(null)} onSave={save}/>}</Page>}

function Sales({sales,onNew}:{sales:Sale[];onNew:()=>void}){const total=sales.reduce((sum,s)=>sum+s.total,0);const rows=sales.map(s=>[s.id,s.items.map(i=>`${i.quantity}× ${i.name}`).join(', '),money(s.total),new Date(s.createdAt).toLocaleDateString('pt-BR'),s.payment]);return <Page title="Vendas" subtitle="Cada venda concluída atualiza o estoque automaticamente" action="＋ Nova venda" onAction={onNew}><section className="stats compact"><Stat icon="R$" tone="orange" label="Faturamento" value={money(total)} detail={`${sales.length} vendas registradas`}/><Stat icon="↗" tone="cyan" label="Ticket médio" value={sales.length?money(total/sales.length):'R$ 0,00'} detail={sales.length?'Calculado automaticamente':'Sem vendas ainda'}/><Stat icon="✓" tone="gold" label="Estoque atualizado" value="Automático" detail="Ao concluir cada venda"/></section><section className="panel data-panel"><div className="inventory-head"><Title title="Vendas recentes" subtitle={`${sales.length} vendas salvas neste aparelho`}/><button className="primary" onClick={onNew}>＋ Registrar venda</button></div>{sales.length?<div className="table-wrap"><table className="responsive-table"><thead><tr><th>Venda</th><th>Itens</th><th>Valor</th><th>Data</th><th>Pagamento</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r[0]}>{r.map((c,j)=><td key={j} data-label={['Venda','Itens','Valor','Data','Pagamento'][j]}>{j===0?<strong>{c}</strong>:c}</td>)}</tr>)}</tbody></table></div>:<EmptyState text="Registre a primeira venda para baixar o estoque automaticamente."/>}</section></Page>}

function Customers({feedback}:{feedback:(x:string)=>void}){return <Page title="Clientes" subtitle="Conheça e fortaleça o relacionamento com seus clientes" action="＋ Novo cliente" onAction={()=>feedback('Cadastro de cliente aberto')}><section className="stats compact"><Stat icon="♙" tone="cyan" label="Total de clientes" value="0" detail="Nenhum cliente"/><Stat icon="★" tone="gold" label="Clientes recorrentes" value="0%" detail="Sem dados"/><Stat icon="R$" tone="orange" label="Valor por cliente" value="R$ 0,00" detail="Sem compras"/></section><DataPanel title="Lista de clientes" headers={['Cliente','Telefone','Histórico','Total gasto','Status']} rows={[]}/></Page>}

function Suppliers({feedback}:{feedback:(x:string)=>void}){return <Page title="Fornecedores" subtitle="Organize parceiros, pedidos e reposições" action="＋ Novo fornecedor" onAction={()=>feedback('Cadastro de fornecedor aberto')}><section className="stats compact"><Stat icon="◇" tone="olive" label="Fornecedores ativos" value="0" detail="Nenhum fornecedor"/><Stat icon="▣" tone="cyan" label="Pedidos em aberto" value="0" detail="R$ 0,00"/><Stat icon="◷" tone="gold" label="Próxima entrega" value="—" detail="Sem entregas"/></section><DataPanel title="Parceiros comerciais" headers={['Fornecedor','Especialidade','Contato','Último pedido','Status']} rows={[]}/></Page>}

function Reports(){return <Page title="Relatórios" subtitle="Indicadores para decisões mais seguras"><section className="panel"><Title title="Relatórios da loja" subtitle="Os indicadores serão calculados com seus dados reais"/><EmptyState text="Cadastre produtos e vendas para gerar relatórios."/></section></Page>}

function Page({title,subtitle,action,onAction,children}:{title:string;subtitle:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <><div className="page-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button className="primary" onClick={onAction}>{action}</button>}</div>{children}</>}
function Stat({icon,tone,label,value,detail,action}:{icon:string;tone:string;label:string;value:string;detail:string;action?:()=>void}){return <article><div className="stat-head"><i className={`ico ${tone}`}>{icon}</i><small>Atualizado agora</small></div><p>{label}</p><strong>{value}</strong>{action?<button className="link" onClick={action}>{detail}</button>:<span className="up">{detail}</span>}</article>}
function Title({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>}
function ProductTable({items,onEdit,onDelete}:{items:Product[];onEdit?:(p:Product)=>void;onDelete?:(p:Product)=>void}){return <div className="table-wrap"><table className="responsive-table"><thead><tr><th>Produto</th><th>Categoria</th><th>Estoque</th><th>Preço</th><th>Status</th>{onEdit&&<th>Ações</th>}</tr></thead><tbody>{items.map((p,i)=><tr key={p.sku}><td data-label="Produto">{p.image?<img className="product-photo" src={p.image} alt=""/>:<b className={`thumb p${i%4}`}>◈</b>}<div><strong>{p.name}</strong><small>SKU: {p.sku}</small></div></td><td data-label="Categoria">{p.category}</td><td data-label="Estoque"><strong>{p.stock} un.</strong></td><td data-label="Preço">R$ {p.price.toFixed(2).replace('.',',')}</td><td data-label="Status"><span className={`status ${p.status==='Em estoque'?'ok':p.status==='Esgotado'?'out':'low'}`}>● {p.status}</span></td>{onEdit&&<td className="row-actions"><button onClick={()=>onEdit(p)}>✎ Editar</button><button className="danger" onClick={()=>onDelete?.(p)}>⌫ Excluir</button></td>}</tr>)}</tbody></table></div>}
function DataPanel({title,headers,rows:_rows}:{title:string;headers:string[];rows:string[][]}){const key=`casa-v3-${title.toLowerCase().replaceAll(' ','-')}`;const [saved,setSaved]=useStored<string[][]>(key,[]);const [editing,setEditing]=useState<{index:number;row:string[]}|null>(null);const remove=(i:number)=>{if(confirm('Deseja excluir este registro?'))setSaved(saved.filter((_,n)=>n!==i))};return <section className="panel data-panel"><div className="inventory-head"><Title title={title} subtitle={`${saved.length} registros salvos`}/><span className="saved-mark">✓ Salvo neste aparelho</span></div>{saved.length===0?<EmptyState text="Nenhum registro cadastrado ainda."/>:<div className="table-wrap"><table className="responsive-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}<th>Ações</th></tr></thead><tbody>{saved.map((r,i)=><tr key={i}>{r.map((c,j)=><td data-label={headers[j]} key={j}>{j===0?<strong>{c}</strong>:j===r.length-1?<span className={`status ${c==='Pendente'?'low':c==='Inativo'?'out':'ok'}`}>● {c}</span>:c}</td>)}<td className="row-actions"><button onClick={()=>setEditing({index:i,row:[...r]})}>✎ Editar</button><button className="danger" onClick={()=>remove(i)}>⌫ Excluir</button></td></tr>)}</tbody></table></div>}{editing&&<RowEditor headers={headers} value={editing.row} onClose={()=>setEditing(null)} onSave={row=>{setSaved(saved.map((r,i)=>i===editing.index?row:r));setEditing(null)}}/>}</section>}

function QuickSale({products,onClose,onComplete}:{products:Product[];onClose:()=>void;onComplete:(sale:Sale)=>void}){const [query,setQuery]=useState('');const [cart,setCart]=useState<{sku:string;name:string;quantity:number;price:number}[]>([]);const [payment,setPayment]=useState('Pix');const available=products.filter(p=>p.stock>0&&(p.name+p.sku).toLowerCase().includes(query.toLowerCase()));const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);const add=(p:Product)=>setCart(current=>{const old=current.find(i=>i.sku===p.sku);return old?current.map(i=>i.sku===p.sku?{...i,quantity:Math.min(i.quantity+1,p.stock)}:i):[...current,{sku:p.sku,name:p.name,quantity:1,price:p.price}]});const change=(sku:string,delta:number)=>setCart(current=>current.flatMap(i=>{if(i.sku!==sku)return [i];const product=products.find(p=>p.sku===sku)!;const quantity=Math.min(product.stock,i.quantity+delta);return quantity>0?[{...i,quantity}]:[]}));const finish=()=>{if(!cart.length)return;onComplete({id:`#${String(Date.now()).slice(-6)}`,items:cart,total,payment,createdAt:new Date().toISOString()})};return <div className="sheet-backdrop" onMouseDown={onClose}><section className="sale-sheet" onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="sheet-title"><div><h2>Nova venda rápida</h2><p>Escolha os itens. O estoque baixa ao concluir.</p></div><button onClick={onClose}>×</button></div><div className="sale-layout"><div className="sale-products"><label className="sale-search">⌕<input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto ou SKU..."/></label><div className="quick-product-list">{available.length?available.map(p=><button key={p.sku} onClick={()=>add(p)}><span>{p.image?<img src={p.image} alt=""/>:'🎣'}</span><div><strong>{p.name}</strong><small>{p.stock} un. disponíveis · {money(p.price)}</small></div><b>＋</b></button>):<p>Nenhum produto disponível.</p>}</div></div><div className="sale-cart"><h3>Itens da venda <small>{cart.reduce((n,i)=>n+i.quantity,0)} item(ns)</small></h3>{cart.length?<div className="cart-lines">{cart.map(item=><div key={item.sku}><div><strong>{item.name}</strong><small>{money(item.price)} cada</small></div><span className="quantity"><button onClick={()=>change(item.sku,-1)}>−</button><b>{item.quantity}</b><button onClick={()=>change(item.sku,1)}>＋</button></span><strong>{money(item.price*item.quantity)}</strong></div>)}</div>:<div className="cart-empty">Adicione os produtos à venda.</div>}<label className="payment-field">Forma de pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Pix</option><option>Dinheiro</option><option>Cartão de crédito</option><option>Cartão de débito</option></select></label><div className="sale-total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary complete-sale" disabled={!cart.length} onClick={finish}>✓ Concluir venda</button></div></div></section></div>}


function ProductEditor({value,onClose,onSave}:{value:Product;onClose:()=>void;onSave:(p:Product)=>void}){const [form,setForm]=useState(value);const [categories,setCategories]=useStored<string[]>('casa-categories-v3',productCategories);const [newCategory,setNewCategory]=useState('');const pickPhoto=async(file?:File)=>{if(file)setForm({...form,image:await resizeProductImage(file)})};const addCategory=()=>{const name=newCategory.trim();if(name&&!categories.some(c=>c.toLowerCase()===name.toLowerCase())){setCategories([...categories,name]);setForm({...form,category:name});setNewCategory('')}};return <div className="sheet-backdrop" onMouseDown={onClose}><form className="edit-sheet" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave({...form,stock:Number(form.stock),price:Number(form.price)})}}><div className="sheet-handle"/><div className="sheet-title"><div><h2>{value.name?'Editar produto':'Novo produto'}</h2><p>As alterações serão salvas neste aparelho.</p></div><button type="button" onClick={onClose}>×</button></div><div className="photo-field"><div className="photo-preview">{form.image?<img src={form.image} alt="Prévia do produto"/>:<span>▧<small>Sem foto</small></span>}</div><div><strong>Foto do produto</strong><p>Escolha da galeria ou tire uma foto.</p><label className="upload-button">⌁ Escolher foto<input type="file" accept="image/*" capture="environment" onChange={e=>pickPhoto(e.target.files?.[0])}/></label>{form.image&&<button className="remove-photo" type="button" onClick={()=>setForm({...form,image:''})}>Remover foto</button>}</div></div><div className="form-grid"><Field label="Nome"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="SKU"><input required disabled={!!value.name} value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></Field><Field label="Categoria"><select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select><span className="new-category"><input placeholder="Nova categoria" value={newCategory} onChange={e=>setNewCategory(e.target.value)}/><button type="button" onClick={addCategory}>＋ Adicionar</button></span></Field><Field label="Estoque"><input required type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></Field><Field label="Preço"><input required type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Em estoque</option><option>Estoque baixo</option><option>Esgotado</option></select></Field></div><div className="sheet-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" type="submit">Salvar produto</button></div></form></div>}
function RowEditor({headers,value,onClose,onSave}:{headers:string[];value:string[];onClose:()=>void;onSave:(x:string[])=>void}){const [form,setForm]=useState(value);return <div className="sheet-backdrop" onMouseDown={onClose}><form className="edit-sheet" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="sheet-handle"/><div className="sheet-title"><div><h2>Editar registro</h2><p>Atualize os dados abaixo.</p></div><button type="button" onClick={onClose}>×</button></div><div className="form-grid">{headers.map((h,i)=><Field label={h} key={h}><input required value={form[i]} onChange={e=>setForm(form.map((x,n)=>n===i?e.target.value:x))}/></Field>)}</div><div className="sheet-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" type="submit">Salvar alterações</button></div></form></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function EmptyState({text}:{text:string}){return <div className="empty-state"><i>＋</i><strong>Tudo pronto para começar</strong><p>{text}</p></div>}
function money(value:number){return `R$ ${value.toFixed(2).replace('.',',')}`}
function useStored<T>(key:string,initial:T){const [value,setValue]=useState<T>(initial);useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved)setValue(JSON.parse(saved))}catch{}},[key]);useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}},[key,value]);return [value,setValue] as const}
function resizeProductImage(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=700,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')?.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.src=String(reader.result)};reader.readAsDataURL(file)})}
