'use client';
import { useMemo, useState } from 'react';

type Product={name:string;sku:string;category:string;stock:number;price:number;status:string};
const products:Product[]=[
 {name:'Vara Marine Sports Evolution',sku:'VAR-001',category:'Varas',stock:18,price:289.9,status:'Em estoque'},
 {name:'Molinete Shimano Sienna 2500',sku:'MOL-018',category:'Molinetes',stock:4,price:449.9,status:'Estoque baixo'},
 {name:'Linha Multifilamento 0,30mm',sku:'LIN-042',category:'Linhas',stock:36,price:79.9,status:'Em estoque'},
 {name:'Isca Artificial Meia Água',sku:'ISC-107',category:'Iscas',stock:0,price:42.5,status:'Esgotado'},
 {name:'Caixa Térmica 34 Litros',sku:'ACE-061',category:'Acessórios',stock:11,price:219.9,status:'Em estoque'},
];
const nav=[['Visão geral','⌂'],['Produtos','▣'],['Vendas','↗'],['Clientes','♙'],['Fornecedores','◇'],['Relatórios','▥']];

export default function Home(){
 const [active,setActive]=useState('Visão geral'); const [query,setQuery]=useState(''); const [notice,setNotice]=useState('');
 const filtered=useMemo(()=>products.filter(p=>(p.name+p.category+p.sku).toLowerCase().includes(query.toLowerCase())),[query]);
 const feedback=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(''),2400)};
 const navigate=(item:string)=>{setActive(item);setQuery('');window.scrollTo({top:0,behavior:'smooth'})};
 return <main className="app-shell">
  <aside className="sidebar">
   <button className="brand" onClick={()=>navigate('Visão geral')} aria-label="Ir para visão geral"><img src="/logo-casa-do-pescador.png" alt="Casa do Pescador"/><span><strong>Casa do Pescador</strong><small>Gestão da loja</small></span></button>
   <nav aria-label="Menu principal">{nav.map(([item,icon])=><button key={item} className={active===item?'active':''} onClick={()=>navigate(item)} aria-current={active===item?'page':undefined}><i>{icon}</i>{item}</button>)}</nav>
   <div className="side-bottom"><button onClick={()=>feedback('Configurações abertas')}><i>⚙</i>Configurações</button><div className="profile"><b>AP</b><span><strong>André Pescador</strong><small>Administrador</small></span><em>⋮</em></div></div>
  </aside>
  <section className="content">
   <header className="topbar"><div><p>Quinta-feira, 27 de agosto</p><h1>{active}</h1></div><div className="actions"><button className="bell" aria-label="Notificações" onClick={()=>feedback('Você não tem novas notificações')}>♢<i/></button><button className="primary" onClick={()=>feedback('Nova venda iniciada')}>＋ Nova venda</button></div></header>
   <div className="dashboard">{active==='Visão geral'?<Overview navigate={navigate}/>:active==='Produtos'?<Products filtered={filtered} query={query} setQuery={setQuery} feedback={feedback}/>:active==='Vendas'?<Sales feedback={feedback}/>:active==='Clientes'?<Customers feedback={feedback}/>:active==='Fornecedores'?<Suppliers feedback={feedback}/>:<Reports/>}</div>
  </section>{notice&&<div className="toast" role="status">✓ {notice}</div>}
 </main>
}

function Overview({navigate}:{navigate:(x:string)=>void}){return <>
 <section className="welcome"><div><span>PAINEL DA LOJA</span><h2>Bom dia, André! 🎣</h2><p>Acompanhe os resultados e mantenha sua operação em dia.</p></div><img src="/logo-casa-do-pescador.png" alt=""/></section>
 <section className="stats"><Stat icon="↗" tone="orange" label="Vendas do dia" value="R$ 3.284,50" detail="↑ 12,5% vs. ontem"/><Stat icon="▣" tone="cyan" label="Pedidos" value="24" detail="↑ 8,2% vs. ontem"/><Stat icon="!" tone="gold" label="Estoque baixo" value="8 itens" detail="Ver produtos →" action={()=>navigate('Produtos')}/><Stat icon="♙" tone="olive" label="Novos clientes" value="38" detail="↑ 5,1% no mês"/></section>
 <section className="middle"><article className="panel sales"><Title title="Desempenho de vendas" subtitle="Receita dos últimos 7 dias"><select aria-label="Período"><option>Últimos 7 dias</option><option>Últimos 30 dias</option></select></Title><div className="chart-summary"><div><span>Receita total</span><strong>R$ 18.740,80</strong></div><span className="up pill">↑ 9,8%</span></div><div className="chart">{[42,58,46,72,64,91,78].map((h,i)=><div className="bar" key={i}><span>{i===5?'4,2k':''}</span><i style={{height:`${h}%`}}/><small>{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'][i]}</small></div>)}</div></article><article className="panel categories"><Title title="Vendas por categoria" subtitle="Distribuição neste mês"/><div className="donut"><div><strong>R$ 54,2k</strong><span>Total</span></div></div><div className="legend">{[['Varas e Molinetes','38%','navy'],['Iscas','26%','orange-dot'],['Linhas e Anzóis','21%','cyan-dot'],['Acessórios','15%','gold-dot']].map(x=><div key={x[0]}><span><i className={x[2]}/>{x[0]}</span><strong>{x[1]}</strong></div>)}</div></article></section>
 <section className="panel inventory"><div className="inventory-head"><Title title="Produtos que precisam de atenção" subtitle="Estoque baixo ou esgotado"/><button className="text-action" onClick={()=>navigate('Produtos')}>Ver estoque completo →</button></div><ProductTable items={products.slice(0,4)}/></section>
 </>}

function Products({filtered,query,setQuery,feedback}:{filtered:Product[];query:string;setQuery:(x:string)=>void;feedback:(x:string)=>void}){return <Page title="Catálogo de produtos" subtitle="Gerencie preços, categorias e níveis de estoque" action="＋ Cadastrar produto" onAction={()=>feedback('Cadastro de produto aberto')}><section className="stats compact"><Stat icon="▣" tone="cyan" label="Produtos cadastrados" value="248" detail="5 categorias"/><Stat icon="!" tone="gold" label="Estoque baixo" value="8" detail="Requer atenção"/><Stat icon="×" tone="orange" label="Esgotados" value="3" detail="Repor estoque"/></section><section className="panel inventory product-page"><div className="inventory-head"><Title title="Todos os produtos" subtitle={`${filtered.length} produtos encontrados`}/><div className="tools"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto..."/></label><button onClick={()=>feedback('Filtros abertos')}>☷ Filtros</button></div></div><ProductTable items={filtered}/></section></Page>}

function Sales({feedback}:{feedback:(x:string)=>void}){const rows=[['#1048','Marcos Silva','R$ 689,80','Hoje, 10:42','Concluída'],['#1047','Ana Paula','R$ 129,90','Hoje, 09:18','Concluída'],['#1046','João Ferreira','R$ 1.240,00','Ontem, 17:35','Pendente'],['#1045','Carlos Souza','R$ 84,50','Ontem, 15:12','Concluída']];return <Page title="Vendas" subtitle="Acompanhe pedidos, pagamentos e faturamento" action="＋ Nova venda" onAction={()=>feedback('Nova venda iniciada')}><section className="stats compact"><Stat icon="R$" tone="orange" label="Faturamento mensal" value="R$ 54.280" detail="↑ 9,8% no mês"/><Stat icon="↗" tone="cyan" label="Ticket médio" value="R$ 184,60" detail="294 vendas"/><Stat icon="◷" tone="gold" label="Vendas pendentes" value="6" detail="R$ 2.180,00"/></section><DataPanel title="Vendas recentes" headers={['Pedido','Cliente','Valor','Data','Status']} rows={rows}/></Page>}

function Customers({feedback}:{feedback:(x:string)=>void}){const rows=[['Marcos Silva','(11) 98842-1290','12 compras','R$ 3.480,50','Ativo'],['Ana Paula Costa','(11) 99714-8812','8 compras','R$ 1.920,30','Ativo'],['João Ferreira','(11) 98551-4470','5 compras','R$ 890,00','Ativo'],['Carlos Souza','(11) 97462-3318','2 compras','R$ 284,50','Inativo']];return <Page title="Clientes" subtitle="Conheça e fortaleça o relacionamento com seus clientes" action="＋ Novo cliente" onAction={()=>feedback('Cadastro de cliente aberto')}><section className="stats compact"><Stat icon="♙" tone="cyan" label="Total de clientes" value="1.284" detail="38 novos este mês"/><Stat icon="★" tone="gold" label="Clientes recorrentes" value="64%" detail="↑ 4% no trimestre"/><Stat icon="R$" tone="orange" label="Valor por cliente" value="R$ 426,80" detail="Média anual"/></section><DataPanel title="Lista de clientes" headers={['Cliente','Telefone','Histórico','Total gasto','Status']} rows={rows}/></Page>}

function Suppliers({feedback}:{feedback:(x:string)=>void}){const rows=[['Marine Sports','Varas e molinetes','(11) 4022-8100','14/08/2026','Ativo'],['Shimano Brasil','Molinetes e carretilhas','(11) 3588-2040','10/08/2026','Ativo'],['Albatroz Fishing','Iscas e acessórios','(19) 3234-7721','02/08/2026','Ativo'],['Pesca Brasil Atacado','Linhas e anzóis','(41) 3091-4450','28/07/2026','Pendente']];return <Page title="Fornecedores" subtitle="Organize parceiros, pedidos e reposições" action="＋ Novo fornecedor" onAction={()=>feedback('Cadastro de fornecedor aberto')}><section className="stats compact"><Stat icon="◇" tone="olive" label="Fornecedores ativos" value="18" detail="4 categorias"/><Stat icon="▣" tone="cyan" label="Pedidos em aberto" value="7" detail="R$ 18.420,00"/><Stat icon="◷" tone="gold" label="Próxima entrega" value="29 ago" detail="Marine Sports"/></section><DataPanel title="Parceiros comerciais" headers={['Fornecedor','Especialidade','Contato','Último pedido','Status']} rows={rows}/></Page>}

function Reports(){return <Page title="Relatórios" subtitle="Indicadores para decisões mais seguras"><section className="report-grid"><article className="panel report-hero"><Title title="Faturamento por mês" subtitle="Comparativo dos últimos 6 meses"/><div className="big-chart">{[48,62,55,73,68,88].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{['Mar','Abr','Mai','Jun','Jul','Ago'][i]}</span></div>)}</div></article><article className="panel goals"><Title title="Meta de agosto" subtitle="Progresso do faturamento"/><div className="goal-ring"><strong>82%</strong></div><h3>R$ 54.280 de R$ 66.000</h3><p>Faltam R$ 11.720 para atingir a meta.</p></article></section><section className="report-cards">{[['Produtos mais vendidos','Vara Evolution, Molinete Sienna e Linha Multi'],['Melhores clientes','Marcos Silva lidera com R$ 3.480,50'],['Margem média','34,8% — alta de 2,1 pontos'],['Giro de estoque','4,2 vezes nos últimos 12 meses']].map(x=><article className="panel" key={x[0]}><i>▥</i><h3>{x[0]}</h3><p>{x[1]}</p><button>Ver relatório →</button></article>)}</section></Page>}

function Page({title,subtitle,action,onAction,children}:{title:string;subtitle:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <><div className="page-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button className="primary" onClick={onAction}>{action}</button>}</div>{children}</>}
function Stat({icon,tone,label,value,detail,action}:{icon:string;tone:string;label:string;value:string;detail:string;action?:()=>void}){return <article><div className="stat-head"><i className={`ico ${tone}`}>{icon}</i><small>Atualizado agora</small></div><p>{label}</p><strong>{value}</strong>{action?<button className="link" onClick={action}>{detail}</button>:<span className="up">{detail}</span>}</article>}
function Title({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>}
function ProductTable({items}:{items:Product[]}){return <div className="table-wrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Estoque</th><th>Preço</th><th>Status</th><th/></tr></thead><tbody>{items.map((p,i)=><tr key={p.sku}><td><b className={`thumb p${i%4}`}>◈</b><div><strong>{p.name}</strong><small>SKU: {p.sku}</small></div></td><td>{p.category}</td><td><strong>{p.stock} un.</strong></td><td>R$ {p.price.toFixed(2).replace('.',',')}</td><td><span className={`status ${p.status==='Em estoque'?'ok':p.status==='Esgotado'?'out':'low'}`}>● {p.status}</span></td><td><button aria-label={`Opções de ${p.name}`}>•••</button></td></tr>)}</tbody></table></div>}
function DataPanel({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <section className="panel data-panel"><div className="inventory-head"><Title title={title} subtitle={`${rows.length} registros recentes`}/><button className="text-action">Exportar ↓</button></div><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0?<strong>{c}</strong>:j===r.length-1?<span className={`status ${c==='Pendente'?'low':c==='Inativo'?'out':'ok'}`}>● {c}</span>:c}</td>)}</tr>)}</tbody></table></div></section>}
